# Generated by Django 4.2.25 on 2025-12-10 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_blocks', '0005_alter_infoblocktag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedinfoblock',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_info_blocks', to='info_blocks.infoblocktag'),
        ),
    ]
