# Generated by Django 4.2.25 on 2025-12-10 22:03

import core.db.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0031_delete_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(db_index=True, help_text="Identifier of filter target, e.g. 'staff:student_search' or 'StudentFilter'", max_length=150)),
                ('data', core.db.fields.PrettyJSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_saved_filters',
                'unique_together': {('user', 'target')},
            },
        ),
    ]
